name: InstaPlots
main: at.instaplots.Main
description: InstaCube Plot System
author: roboalex2
version: ${project.version}
api-version: 1.15
load: POSTWORLD
depend: [InstaBaseAPI]
commands:
  plot:
    description: Manage you Plot